gazebo_ros_control:
  pid_gains:
    campero_ur10_elbow_joint:
      p: 10.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    campero_ur10_shoulder_lift_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    campero_ur10_shoulder_pan_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    
    campero_ur10_wrist_1_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    campero_ur10_wrist_2_joint:
      p: 200.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    campero_ur10_wrist_3_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    campero_front_ptz_camera_pan_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    campero_front_ptz_camera_tilt_joint:
      p: 100.0
      i: 0.01
      d: 10.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
