(cl:defpackage campero_pad-srv
  (:use )
  (:export
   "ENABLE_DISABLE_PAD"
   "<ENABLE_DISABLE_PAD-REQUEST>"
   "ENABLE_DISABLE_PAD-REQUEST"
   "<ENABLE_DISABLE_PAD-RESPONSE>"
   "ENABLE_DISABLE_PAD-RESPONSE"
  ))

