// Generated by gencpp from file campero_pad/enable_disable_padRequest.msg
// DO NOT EDIT!


#ifndef CAMPERO_PAD_MESSAGE_ENABLE_DISABLE_PADREQUEST_H
#define CAMPERO_PAD_MESSAGE_ENABLE_DISABLE_PADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace campero_pad
{
template <class ContainerAllocator>
struct enable_disable_padRequest_
{
  typedef enable_disable_padRequest_<ContainerAllocator> Type;

  enable_disable_padRequest_()
    : value(false)  {
    }
  enable_disable_padRequest_(const ContainerAllocator& _alloc)
    : value(false)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> const> ConstPtr;

}; // struct enable_disable_padRequest_

typedef ::campero_pad::enable_disable_padRequest_<std::allocator<void> > enable_disable_padRequest;

typedef boost::shared_ptr< ::campero_pad::enable_disable_padRequest > enable_disable_padRequestPtr;
typedef boost::shared_ptr< ::campero_pad::enable_disable_padRequest const> enable_disable_padRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::campero_pad::enable_disable_padRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace campero_pad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const ::campero_pad::enable_disable_padRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe431d687bf4b2c65ULL;
  static const uint64_t static_value2 = 0xfbd94b12ae0cb5d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "campero_pad/enable_disable_padRequest";
  }

  static const char* value(const ::campero_pad::enable_disable_padRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool value\n\
";
  }

  static const char* value(const ::campero_pad::enable_disable_padRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enable_disable_padRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::campero_pad::enable_disable_padRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::campero_pad::enable_disable_padRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMPERO_PAD_MESSAGE_ENABLE_DISABLE_PADREQUEST_H
