// Generated by gencpp from file map_nav_manager/SetFilenameRequest.msg
// DO NOT EDIT!


#ifndef MAP_NAV_MANAGER_MESSAGE_SETFILENAMEREQUEST_H
#define MAP_NAV_MANAGER_MESSAGE_SETFILENAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_nav_manager
{
template <class ContainerAllocator>
struct SetFilenameRequest_
{
  typedef SetFilenameRequest_<ContainerAllocator> Type;

  SetFilenameRequest_()
    : name()
    , use_it_by_default(false)  {
    }
  SetFilenameRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , use_it_by_default(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _use_it_by_default_type;
  _use_it_by_default_type use_it_by_default;





  typedef boost::shared_ptr< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFilenameRequest_

typedef ::map_nav_manager::SetFilenameRequest_<std::allocator<void> > SetFilenameRequest;

typedef boost::shared_ptr< ::map_nav_manager::SetFilenameRequest > SetFilenameRequestPtr;
typedef boost::shared_ptr< ::map_nav_manager::SetFilenameRequest const> SetFilenameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_nav_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'map_nav_manager': ['/home/pc-campero2/campero_ws/src/campero/map_nav_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31dc38e110189d0445c48b5db718a57d";
  }

  static const char* value(const ::map_nav_manager::SetFilenameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31dc38e110189d04ULL;
  static const uint64_t static_value2 = 0x45c48b5db718a57dULL;
};

template<class ContainerAllocator>
struct DataType< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_nav_manager/SetFilenameRequest";
  }

  static const char* value(const ::map_nav_manager::SetFilenameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
\n\
bool use_it_by_default\n\
";
  }

  static const char* value(const ::map_nav_manager::SetFilenameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.use_it_by_default);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFilenameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_nav_manager::SetFilenameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_nav_manager::SetFilenameRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "use_it_by_default: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_it_by_default);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_NAV_MANAGER_MESSAGE_SETFILENAMEREQUEST_H
