joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: campero_back_left_wheel_joint
joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: campero_back_right_wheel_joint
joint_frw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: campero_front_right_wheel_joint
joint_flw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: campero_front_left_wheel_joint

  
robotnik_base_control:
  type: campero_controller/CamperoController
  joint:
    front_right_wheel_joint:
      name: campero_front_right_wheel_joint
      max_speed: 27.27 # rad/s
    front_left_wheel_joint:
      name: campero_front_left_wheel_joint
      max_speed: 27.27 # rad/s
    back_right_wheel_joint:
      name: campero_back_right_wheel_joint
      max_speed: 27.27 # rad/s
    back_left_wheel_joint:
      name: campero_back_left_wheel_joint
      max_speed: 27.27 # rad/s
  linear_speed_limit: 1.5 # m/s
  linear_acceleration_limit: 1.5 # m/s^2
  angular_speed_limit: 0.5 # rad/s
  angular_acceleration_limit: 1 # rad/s^2
  odom_frame: campero_odom
  robot_base_frame: campero_base_footprint
  odom_broadcast_tf: true
  odom_topic: 'robotnik_base_control/odom'
  wheel_base: 0.59
  track_width: 0.69
  wheel_diameter: 0.254
  cmd_watchdog_duration: 0.2
  imu_watchdog_duration: 0.1
  imu_topic: imu/data
  odom_publish_frequency: 100
  cmd_vel        : 'robotnik_base_control/cmd_vel'
  kinematic_mode : 'omni'
  motion_odometry: true
  in_motion_timer: 2.0






#joint_pan_position_controller:
#  type: position_controllers/JointPositionController
#  joint: joint_camera_pan
#joint_tilt_position_controller:
#  type: position_controllers/JointPositionController
#  joint: joint_camera_tilt

robotnik_base_control_diff:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['campero_front_left_wheel_joint','campero_back_left_wheel_joint']
  right_wheel : ['campero_front_right_wheel_joint','campero_back_right_wheel_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.590 #ancho rueda+separacion entre ruedas (CAMPERO RUBBER)
  wheel_radius : 0.177 # (CAMPERO RUBBER)

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: campero_base_footprint
  odom_frame_id: campero_odom
  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 3.0 #1.5 # m/s
      min_velocity           : -3.0 #-1.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.00  # m/s^2
      min_acceleration       : -6.0 #-3.00 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.0 #3.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 #3.0  # rad/s^2

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - campero_ur10_shoulder_pan_joint
     - campero_ur10_shoulder_lift_joint
     - campero_ur10_elbow_joint
     - campero_ur10_wrist_1_joint
     - campero_ur10_wrist_2_joint
     - campero_ur10_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    campero_ur10_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    campero_ur10_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    campero_ur10_elbow_joint: {trajectory: 0.1, goal: 0.1}
    campero_ur10_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    campero_ur10_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    campero_ur10_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - campero_palm_finger_1_joint
     - campero_palm_finger_2_joint
     - campero_finger_middle_joint_1
     - campero_finger_middle_joint_2
     - campero_finger_middle_joint_3
     - campero_finger_1_joint_1
     - campero_finger_1_joint_2
     - campero_finger_1_joint_3
     - campero_finger_2_joint_1
     - campero_finger_2_joint_2
     - campero_finger_2_joint_3
     
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10


joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0

joint_palm_finger_1_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_palm_finger_1_joint
joint_palm_finger_2_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_palm_finger_2_joint
  
  
joint_finger_middle_1_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_middle_joint_1
joint_finger_middle_2_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_middle_joint_2
joint_finger_middle_3_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_middle_joint_3
  
  
joint_finger_1_1_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_1_joint_1
joint_finger_1_2_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_1_joint_2
joint_finger_1_3_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_1_joint_3
  
joint_finger_2_1_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_2_joint_1
joint_finger_2_2_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_2_joint_2
joint_finger_2_3_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_finger_2_joint_3
  
joint_robotiq_85_left_knuckle_position_controller:
  type: position_controllers/JointPositionController
  joint: campero_robotiq_85_left_knuckle_joint

