// Generated by gencpp from file robotnik_msgs/BatteryDockingStatus.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_BATTERYDOCKINGSTATUS_H
#define ROBOTNIK_MSGS_MESSAGE_BATTERYDOCKINGSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct BatteryDockingStatus_
{
  typedef BatteryDockingStatus_<ContainerAllocator> Type;

  BatteryDockingStatus_()
    : operation_mode()
    , battery_current(0.0)
    , contact_relay_status(false)
    , charger_relay_status(false)  {
    }
  BatteryDockingStatus_(const ContainerAllocator& _alloc)
    : operation_mode(_alloc)
    , battery_current(0.0)
    , contact_relay_status(false)
    , charger_relay_status(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _operation_mode_type;
  _operation_mode_type operation_mode;

   typedef float _battery_current_type;
  _battery_current_type battery_current;

   typedef uint8_t _contact_relay_status_type;
  _contact_relay_status_type contact_relay_status;

   typedef uint8_t _charger_relay_status_type;
  _charger_relay_status_type charger_relay_status;




  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  MODE_DISABLED;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  MODE_AUTO_HW;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  MODE_AUTO_SW;
  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  MODE_MANUAL_SW;

  typedef boost::shared_ptr< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryDockingStatus_

typedef ::robotnik_msgs::BatteryDockingStatus_<std::allocator<void> > BatteryDockingStatus;

typedef boost::shared_ptr< ::robotnik_msgs::BatteryDockingStatus > BatteryDockingStatusPtr;
typedef boost::shared_ptr< ::robotnik_msgs::BatteryDockingStatus const> BatteryDockingStatusConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      BatteryDockingStatus_<ContainerAllocator>::MODE_DISABLED =
        
          "disabled"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      BatteryDockingStatus_<ContainerAllocator>::MODE_AUTO_HW =
        
          "automatic_hw"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      BatteryDockingStatus_<ContainerAllocator>::MODE_AUTO_SW =
        
          "automatic_sw"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      BatteryDockingStatus_<ContainerAllocator>::MODE_MANUAL_SW =
        
          "manual_sw"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16af3d7230e4454981667998006e8e68";
  }

  static const char* value(const ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16af3d7230e44549ULL;
  static const uint64_t static_value2 = 0x81667998006e8e68ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/BatteryDockingStatus";
  }

  static const char* value(const ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Modes of operation:\n\
# no docking station contacts\n\
string MODE_DISABLED=disabled\n\
# Unattended relay detection & activation with no inputs/outputs feedback. Done by the hw\n\
string MODE_AUTO_HW=automatic_hw\n\
# Unattended relay detection & activation with inputs/outputs feedback. Done by the sw\n\
string MODE_AUTO_SW=automatic_sw\n\
# Unattended relay detection & and manual activation of the charging relay\n\
string MODE_MANUAL_SW=manual_sw\n\
\n\
string operation_mode\n\
	\n\
float32 battery_current		# current flow in Amperes\n\
bool contact_relay_status	# shows if there's contact with the charger\n\
bool charger_relay_status   # shows if the relay for the charge is active or not\n\
";
  }

  static const char* value(const ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation_mode);
      stream.next(m.battery_current);
      stream.next(m.contact_relay_status);
      stream.next(m.charger_relay_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryDockingStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::BatteryDockingStatus_<ContainerAllocator>& v)
  {
    s << indent << "operation_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.operation_mode);
    s << indent << "battery_current: ";
    Printer<float>::stream(s, indent + "  ", v.battery_current);
    s << indent << "contact_relay_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.contact_relay_status);
    s << indent << "charger_relay_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.charger_relay_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_BATTERYDOCKINGSTATUS_H
