// Generated by gencpp from file robotnik_msgs/SetElevatorResult.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SETELEVATORRESULT_H
#define ROBOTNIK_MSGS_MESSAGE_SETELEVATORRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/ElevatorStatus.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct SetElevatorResult_
{
  typedef SetElevatorResult_<ContainerAllocator> Type;

  SetElevatorResult_()
    : result(false)
    , status()  {
    }
  SetElevatorResult_(const ContainerAllocator& _alloc)
    : result(false)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef  ::robotnik_msgs::ElevatorStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetElevatorResult_

typedef ::robotnik_msgs::SetElevatorResult_<std::allocator<void> > SetElevatorResult;

typedef boost::shared_ptr< ::robotnik_msgs::SetElevatorResult > SetElevatorResultPtr;
typedef boost::shared_ptr< ::robotnik_msgs::SetElevatorResult const> SetElevatorResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "247f8f0d4edf8e0b2ea11d3758b71b4f";
  }

  static const char* value(const ::robotnik_msgs::SetElevatorResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x247f8f0d4edf8e0bULL;
  static const uint64_t static_value2 = 0x2ea11d3758b71b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/SetElevatorResult";
  }

  static const char* value(const ::robotnik_msgs::SetElevatorResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool result\n\
robotnik_msgs/ElevatorStatus status\n\
\n\
================================================================================\n\
MSG: robotnik_msgs/ElevatorStatus\n\
# state\n\
string RAISING=raising\n\
string LOWERING=lowering\n\
string IDLE=idle\n\
string ERROR_G_IO=error_getting_io\n\
string ERROR_S_IO=error_setting_io\n\
string ERROR_TIMEOUT=error_timeout_in_action\n\
# position\n\
string UP=up\n\
string DOWN=down\n\
string UNKNOWN=unknown\n\
# IDLE, RAISING, LOWERING\n\
string state\n\
# UP, DOWN, UNKNOWN\n\
string position\n\
float32 height\n\
";
  }

  static const char* value(const ::robotnik_msgs::SetElevatorResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetElevatorResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::SetElevatorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::SetElevatorResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::robotnik_msgs::ElevatorStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SETELEVATORRESULT_H
