// Generated by gencpp from file robotnik_msgs/SetEncoderTurnsRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SETENCODERTURNSREQUEST_H
#define ROBOTNIK_MSGS_MESSAGE_SETENCODERTURNSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/MotorHeadingOffset.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct SetEncoderTurnsRequest_
{
  typedef SetEncoderTurnsRequest_<ContainerAllocator> Type;

  SetEncoderTurnsRequest_()
    : encoder_turns()  {
    }
  SetEncoderTurnsRequest_(const ContainerAllocator& _alloc)
    : encoder_turns(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotnik_msgs::MotorHeadingOffset_<ContainerAllocator>  _encoder_turns_type;
  _encoder_turns_type encoder_turns;





  typedef boost::shared_ptr< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEncoderTurnsRequest_

typedef ::robotnik_msgs::SetEncoderTurnsRequest_<std::allocator<void> > SetEncoderTurnsRequest;

typedef boost::shared_ptr< ::robotnik_msgs::SetEncoderTurnsRequest > SetEncoderTurnsRequestPtr;
typedef boost::shared_ptr< ::robotnik_msgs::SetEncoderTurnsRequest const> SetEncoderTurnsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09518a7439d03092a98d4a07f8bc5cf9";
  }

  static const char* value(const ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09518a7439d03092ULL;
  static const uint64_t static_value2 = 0xa98d4a07f8bc5cf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/SetEncoderTurnsRequest";
  }

  static const char* value(const ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/MotorHeadingOffset encoder_turns\n\
\n\
================================================================================\n\
MSG: robotnik_msgs/MotorHeadingOffset\n\
int32 motor\n\
int32 value\n\
";
  }

  static const char* value(const ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder_turns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEncoderTurnsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::SetEncoderTurnsRequest_<ContainerAllocator>& v)
  {
    s << indent << "encoder_turns: ";
    s << std::endl;
    Printer< ::robotnik_msgs::MotorHeadingOffset_<ContainerAllocator> >::stream(s, indent + "  ", v.encoder_turns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SETENCODERTURNSREQUEST_H
