// Generated by gencpp from file robotnik_msgs/GetMotorsHeadingOffsetResponse.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_GETMOTORSHEADINGOFFSETRESPONSE_H
#define ROBOTNIK_MSGS_MESSAGE_GETMOTORSHEADINGOFFSETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/MotorHeadingOffset.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct GetMotorsHeadingOffsetResponse_
{
  typedef GetMotorsHeadingOffsetResponse_<ContainerAllocator> Type;

  GetMotorsHeadingOffsetResponse_()
    : offsets()  {
    }
  GetMotorsHeadingOffsetResponse_(const ContainerAllocator& _alloc)
    : offsets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robotnik_msgs::MotorHeadingOffset_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robotnik_msgs::MotorHeadingOffset_<ContainerAllocator> >::other >  _offsets_type;
  _offsets_type offsets;





  typedef boost::shared_ptr< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMotorsHeadingOffsetResponse_

typedef ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<std::allocator<void> > GetMotorsHeadingOffsetResponse;

typedef boost::shared_ptr< ::robotnik_msgs::GetMotorsHeadingOffsetResponse > GetMotorsHeadingOffsetResponsePtr;
typedef boost::shared_ptr< ::robotnik_msgs::GetMotorsHeadingOffsetResponse const> GetMotorsHeadingOffsetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d322475eaf1465784a3a443c8adce632";
  }

  static const char* value(const ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd322475eaf146578ULL;
  static const uint64_t static_value2 = 0x4a3a443c8adce632ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/GetMotorsHeadingOffsetResponse";
  }

  static const char* value(const ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/MotorHeadingOffset[] offsets\n\
\n\
\n\
================================================================================\n\
MSG: robotnik_msgs/MotorHeadingOffset\n\
int32 motor\n\
int32 value\n\
";
  }

  static const char* value(const ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offsets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMotorsHeadingOffsetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::GetMotorsHeadingOffsetResponse_<ContainerAllocator>& v)
  {
    s << indent << "offsets[]" << std::endl;
    for (size_t i = 0; i < v.offsets.size(); ++i)
    {
      s << indent << "  offsets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robotnik_msgs::MotorHeadingOffset_<ContainerAllocator> >::stream(s, indent + "    ", v.offsets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_GETMOTORSHEADINGOFFSETRESPONSE_H
