// Generated by gencpp from file robotnik_msgs/ResetFromSubStateRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATEREQUEST_H
#define ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct ResetFromSubStateRequest_
{
  typedef ResetFromSubStateRequest_<ContainerAllocator> Type;

  ResetFromSubStateRequest_()
    : subState(0)  {
    }
  ResetFromSubStateRequest_(const ContainerAllocator& _alloc)
    : subState(0)  {
  (void)_alloc;
    }



   typedef int32_t _subState_type;
  _subState_type subState;





  typedef boost::shared_ptr< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetFromSubStateRequest_

typedef ::robotnik_msgs::ResetFromSubStateRequest_<std::allocator<void> > ResetFromSubStateRequest;

typedef boost::shared_ptr< ::robotnik_msgs::ResetFromSubStateRequest > ResetFromSubStateRequestPtr;
typedef boost::shared_ptr< ::robotnik_msgs::ResetFromSubStateRequest const> ResetFromSubStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5b79633cee30f5c84879c01bef7033a";
  }

  static const char* value(const ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5b79633cee30f5cULL;
  static const uint64_t static_value2 = 0x84879c01bef7033aULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/ResetFromSubStateRequest";
  }

  static const char* value(const ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 subState\n\
\n\
";
  }

  static const char* value(const ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetFromSubStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::ResetFromSubStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "subState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.subState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_RESETFROMSUBSTATEREQUEST_H
