// Generated by gencpp from file robotnik_msgs/SetMotorPIDRequest.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_SETMOTORPIDREQUEST_H
#define ROBOTNIK_MSGS_MESSAGE_SETMOTORPIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotnik_msgs/MotorPID.h>

namespace robotnik_msgs
{
template <class ContainerAllocator>
struct SetMotorPIDRequest_
{
  typedef SetMotorPIDRequest_<ContainerAllocator> Type;

  SetMotorPIDRequest_()
    : pid()  {
    }
  SetMotorPIDRequest_(const ContainerAllocator& _alloc)
    : pid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotnik_msgs::MotorPID_<ContainerAllocator>  _pid_type;
  _pid_type pid;





  typedef boost::shared_ptr< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMotorPIDRequest_

typedef ::robotnik_msgs::SetMotorPIDRequest_<std::allocator<void> > SetMotorPIDRequest;

typedef boost::shared_ptr< ::robotnik_msgs::SetMotorPIDRequest > SetMotorPIDRequestPtr;
typedef boost::shared_ptr< ::robotnik_msgs::SetMotorPIDRequest const> SetMotorPIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c1e18bd557fca88ee3a5e13186ec0ee";
  }

  static const char* value(const ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c1e18bd557fca88ULL;
  static const uint64_t static_value2 = 0xee3a5e13186ec0eeULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/SetMotorPIDRequest";
  }

  static const char* value(const ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorPID pid\n\
\n\
================================================================================\n\
MSG: robotnik_msgs/MotorPID\n\
# either can_id or name are set\n\
# if can_id is -1, then this refers to all motors.\n\
int32[] can_id\n\
string[] name\n\
float32[] kp\n\
float32[] ki\n\
float32[] kd\n\
";
  }

  static const char* value(const ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMotorPIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::SetMotorPIDRequest_<ContainerAllocator>& v)
  {
    s << indent << "pid: ";
    s << std::endl;
    Printer< ::robotnik_msgs::MotorPID_<ContainerAllocator> >::stream(s, indent + "  ", v.pid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_SETMOTORPIDREQUEST_H
