// Generated by gencpp from file robotnik_msgs/StringArray.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_MSGS_MESSAGE_STRINGARRAY_H
#define ROBOTNIK_MSGS_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_msgs
{
template <class ContainerAllocator>
struct StringArray_
{
  typedef StringArray_<ContainerAllocator> Type;

  StringArray_()
    : text()  {
    }
  StringArray_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::robotnik_msgs::StringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_msgs::StringArray_<ContainerAllocator> const> ConstPtr;

}; // struct StringArray_

typedef ::robotnik_msgs::StringArray_<std::allocator<void> > StringArray;

typedef boost::shared_ptr< ::robotnik_msgs::StringArray > StringArrayPtr;
typedef boost::shared_ptr< ::robotnik_msgs::StringArray const> StringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_msgs::StringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_msgs::StringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::StringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_msgs::StringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da62ad767a4dbff3a3ce44939e6c55e8";
  }

  static const char* value(const ::robotnik_msgs::StringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda62ad767a4dbff3ULL;
  static const uint64_t static_value2 = 0xa3ce44939e6c55e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_msgs/StringArray";
  }

  static const char* value(const ::robotnik_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] text\n\
";
  }

  static const char* value(const ::robotnik_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_msgs::StringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_msgs::StringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_msgs::StringArray_<ContainerAllocator>& v)
  {
    s << indent << "text[]" << std::endl;
    for (size_t i = 0; i < v.text.size(); ++i)
    {
      s << indent << "  text[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_MSGS_MESSAGE_STRINGARRAY_H
