// Generated by gencpp from file axis_camera/set_digital_outputRequest.msg
// DO NOT EDIT!


#ifndef AXIS_CAMERA_MESSAGE_SET_DIGITAL_OUTPUTREQUEST_H
#define AXIS_CAMERA_MESSAGE_SET_DIGITAL_OUTPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace axis_camera
{
template <class ContainerAllocator>
struct set_digital_outputRequest_
{
  typedef set_digital_outputRequest_<ContainerAllocator> Type;

  set_digital_outputRequest_()
    : output(0)
    , value(false)  {
    }
  set_digital_outputRequest_(const ContainerAllocator& _alloc)
    : output(0)
    , value(false)  {
  (void)_alloc;
    }



   typedef int8_t _output_type;
  _output_type output;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_digital_outputRequest_

typedef ::axis_camera::set_digital_outputRequest_<std::allocator<void> > set_digital_outputRequest;

typedef boost::shared_ptr< ::axis_camera::set_digital_outputRequest > set_digital_outputRequestPtr;
typedef boost::shared_ptr< ::axis_camera::set_digital_outputRequest const> set_digital_outputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::axis_camera::set_digital_outputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace axis_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'axis_camera': ['/home/pc-campero2/campero_ws/src/campero/axis_camera/msg', '/home/pc-campero2/campero_ws/src/campero/axis_camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robotnik_msgs': ['/home/pc-campero2/campero_ws/src/campero/robotnik_msgs/msg', '/home/pc-campero2/campero_ws/devel/share/robotnik_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1dc4e43688f0a8d32bc10e72fd189d2";
  }

  static const char* value(const ::axis_camera::set_digital_outputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1dc4e43688f0a8dULL;
  static const uint64_t static_value2 = 0x32bc10e72fd189d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "axis_camera/set_digital_outputRequest";
  }

  static const char* value(const ::axis_camera::set_digital_outputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 output\n\
bool value\n\
";
  }

  static const char* value(const ::axis_camera::set_digital_outputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_digital_outputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::axis_camera::set_digital_outputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::axis_camera::set_digital_outputRequest_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int8_t>::stream(s, indent + "  ", v.output);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AXIS_CAMERA_MESSAGE_SET_DIGITAL_OUTPUTREQUEST_H
