// Generated by gencpp from file poi_manager/LabeledPose.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MESSAGE_LABELEDPOSE_H
#define POI_MANAGER_MESSAGE_LABELEDPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace poi_manager
{
template <class ContainerAllocator>
struct LabeledPose_
{
  typedef LabeledPose_<ContainerAllocator> Type;

  LabeledPose_()
    : label()
    , pose()  {
    }
  LabeledPose_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::poi_manager::LabeledPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_manager::LabeledPose_<ContainerAllocator> const> ConstPtr;

}; // struct LabeledPose_

typedef ::poi_manager::LabeledPose_<std::allocator<void> > LabeledPose;

typedef boost::shared_ptr< ::poi_manager::LabeledPose > LabeledPosePtr;
typedef boost::shared_ptr< ::poi_manager::LabeledPose const> LabeledPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_manager::LabeledPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_manager::LabeledPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'poi_manager': ['/home/pc-campero2/campero_ws/src/campero/poi_manager/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager::LabeledPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager::LabeledPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager::LabeledPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager::LabeledPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager::LabeledPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager::LabeledPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_manager::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a1ec64bf005e8c3b1f7ef1b49fd5d1e";
  }

  static const char* value(const ::poi_manager::LabeledPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a1ec64bf005e8c3ULL;
  static const uint64_t static_value2 = 0xb1f7ef1b49fd5d1eULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_manager::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_manager/LabeledPose";
  }

  static const char* value(const ::poi_manager::LabeledPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_manager::LabeledPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
geometry_msgs/Pose2D pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::poi_manager::LabeledPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_manager::LabeledPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LabeledPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_manager::LabeledPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_manager::LabeledPose_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_MANAGER_MESSAGE_LABELEDPOSE_H
