// Generated by gencpp from file poi_manager/ReadPOIs.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MESSAGE_READPOIS_H
#define POI_MANAGER_MESSAGE_READPOIS_H

#include <ros/service_traits.h>


#include <poi_manager/ReadPOIsRequest.h>
#include <poi_manager/ReadPOIsResponse.h>


namespace poi_manager
{

struct ReadPOIs
{

typedef ReadPOIsRequest Request;
typedef ReadPOIsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadPOIs
} // namespace poi_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poi_manager::ReadPOIs > {
  static const char* value()
  {
    return "c28755b56158f239ec1c46a03550b3d2";
  }

  static const char* value(const ::poi_manager::ReadPOIs&) { return value(); }
};

template<>
struct DataType< ::poi_manager::ReadPOIs > {
  static const char* value()
  {
    return "poi_manager/ReadPOIs";
  }

  static const char* value(const ::poi_manager::ReadPOIs&) { return value(); }
};


// service_traits::MD5Sum< ::poi_manager::ReadPOIsRequest> should match 
// service_traits::MD5Sum< ::poi_manager::ReadPOIs > 
template<>
struct MD5Sum< ::poi_manager::ReadPOIsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poi_manager::ReadPOIs >::value();
  }
  static const char* value(const ::poi_manager::ReadPOIsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_manager::ReadPOIsRequest> should match 
// service_traits::DataType< ::poi_manager::ReadPOIs > 
template<>
struct DataType< ::poi_manager::ReadPOIsRequest>
{
  static const char* value()
  {
    return DataType< ::poi_manager::ReadPOIs >::value();
  }
  static const char* value(const ::poi_manager::ReadPOIsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poi_manager::ReadPOIsResponse> should match 
// service_traits::MD5Sum< ::poi_manager::ReadPOIs > 
template<>
struct MD5Sum< ::poi_manager::ReadPOIsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poi_manager::ReadPOIs >::value();
  }
  static const char* value(const ::poi_manager::ReadPOIsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_manager::ReadPOIsResponse> should match 
// service_traits::DataType< ::poi_manager::ReadPOIs > 
template<>
struct DataType< ::poi_manager::ReadPOIsResponse>
{
  static const char* value()
  {
    return DataType< ::poi_manager::ReadPOIs >::value();
  }
  static const char* value(const ::poi_manager::ReadPOIsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POI_MANAGER_MESSAGE_READPOIS_H
