// Generated by gencpp from file poi_manager/UpdatePOIsResponse.msg
// DO NOT EDIT!


#ifndef POI_MANAGER_MESSAGE_UPDATEPOISRESPONSE_H
#define POI_MANAGER_MESSAGE_UPDATEPOISRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace poi_manager
{
template <class ContainerAllocator>
struct UpdatePOIsResponse_
{
  typedef UpdatePOIsResponse_<ContainerAllocator> Type;

  UpdatePOIsResponse_()
    : empty()  {
    }
  UpdatePOIsResponse_(const ContainerAllocator& _alloc)
    : empty(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _empty_type;
  _empty_type empty;





  typedef boost::shared_ptr< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdatePOIsResponse_

typedef ::poi_manager::UpdatePOIsResponse_<std::allocator<void> > UpdatePOIsResponse;

typedef boost::shared_ptr< ::poi_manager::UpdatePOIsResponse > UpdatePOIsResponsePtr;
typedef boost::shared_ptr< ::poi_manager::UpdatePOIsResponse const> UpdatePOIsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'poi_manager': ['/home/pc-campero2/campero_ws/src/campero/poi_manager/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aac6c697d5414bc0fcede8c33981d0e";
  }

  static const char* value(const ::poi_manager::UpdatePOIsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aac6c697d5414bcULL;
  static const uint64_t static_value2 = 0x0fcede8c33981d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_manager/UpdatePOIsResponse";
  }

  static const char* value(const ::poi_manager::UpdatePOIsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Empty empty\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Empty\n\
";
  }

  static const char* value(const ::poi_manager::UpdatePOIsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.empty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdatePOIsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_manager::UpdatePOIsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_manager::UpdatePOIsResponse_<ContainerAllocator>& v)
  {
    s << indent << "empty: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.empty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_MANAGER_MESSAGE_UPDATEPOISRESPONSE_H
